### ISSUE TITLE
Need any help?

### ISSUE THREAD

**Issue by cdunn2001** [skynetservices/skynet-archive#1]
Would you like any help on this project? If so, maybe we can use GitHub's issue-tracker, so that people don't work on the same thing at the same time.

**Comment by bketelsen** [comment]
Absolutely!  I'll organize my ideas and plans into some easy to bite off issues.

**Comment by bketelsen** [comment]
14 new issues added.  Pick one that makes some sense on its own and doesn't have too many dependencies on the others and enjoy!
