### ISSUE TITLE
Change the transport of RPC calls

### ISSUE THREAD

**Issue by bketelsen** [skynetservices/skynet-archive#10]
EDITED:  Change all nodes to support both GOB and JSON-RPC

**Comment by cdunn2001** [comment]
I was studying RPC last night. Doozer uses ProtocolBuffers, but that's just data, not methods. Go's RPC uses introspection to discover methods. To use PB or some others, we would need to copy some of that introspection code into skylib.

I'll look into the ones you mentioned, but I am thinking JSON-RPC is probably the best choice for now. First, we need to re-factor the RPC calls into skylib, to hide RPC from client code. Then, we'll be more free to alter the protocol. Is that what you had in mind?

**Comment by cdunn2001** [comment]
Ok. "rpc" is a nice package. We will use its "Codec" interface. "jsonrpc" is an example of a json-rpc codec, and we can create more for other protocols (if they don't already exist).

I'll alter the codebase to use the jsonrpc codec. That will make it more clear. Then I'll show you the code, but not push yet. I want to set up testing first.

It would be nice if we could test without doozer. Maybe that's another thing to abstract out. Hmmm....

**Comment by bketelsen** [comment]
I would like to see performance testing before and after on go's RPC vs JSON-RPC.  Go has nice benchmarking framework for this.

**Comment by cdunn2001** [comment]
Ok.

**Comment by cdunn2001** [comment]
I'll bet that [**gob**](http://golang.org/pkg/gob/) (the default) is faster than either **jsonrpc** or **xmlrpc** (if we can find that). But **gob** is Go-specific. Let's make the benchmarking a separate Issue.

**Comment by bketelsen** [comment]
That's why I'm sure we'll end up with PB or MsgPack or Json-RPC when we get to the point that we're cross platform.

**Comment by cdunn2001** [comment]
I tried to use **rpc**'s http support with a different protocol. Unfortunately, the **gob** codec is hard-wired. It's possible to copy **rpc** and alter it, but ... Anyway, **rpc** should work fine with simple **net** servers. We just lose the debug view in the browser. I did copy the codec for the **gob** server though -- just for benchmarking.

(The reason why **rpc**'s http is so closely tied to the codec is that the codec operates on a "hijacked" http connection, after the initial `CONNECT`. From that point on, http is not even used.)

Ok. I got **jsonrpc** working for the `service.go` server. There are some problems with exiting goroutines (a watcher, maybe?) but the web page works. It's just a handful of changes, for now. If you want to try it:
`
git remote add cd git://github.com/cdunn2001/skynet.git
git fetch cd
git checkout cd/jsonrpc
`
As you can see, the initiators contact the router using "html-rpc". The router contacts the server via "jsonrpc". Making it work with generic codecs would be more work. Later. I want to figure out the bugs first.

**Comment by bketelsen** [comment]
Interesting.  Did you do any benchmarks?  In order to make this work, you would want to change the RouteGetUserDataRequest function to call the callRpcService function passing in the protocol parameter.  The protocol could be part of the config stored in Doozer.  Then there could be any number of protocols supported.

**Comment by cdunn2001** [comment]
That makes sense. However, if the protocol changes in doozer, I think we have a race condition.

No benchmarking yet. I wanted to write a file-based alternative to doozer first -- using `syscall.Flock()` -- but it's taking awhile. Maybe I should concentrate on a simpler initiator, one which just pumps out a series of random words to a server, and a server which reverses and returns them.

**Comment by bketelsen** [comment]
Just flew by on Twitter : ruby object serialization library benchmark results, 100k runs: json: 4.7s, bert: 22s, marshal: 1.5s, message pack: 0.6s. crazy.

Message Pack seems like a very nice option for fast serialization.

**Comment by bketelsen** [comment]
I debated this online with @paulosuzart and I think it makes the most sense to support at least Gob and JSON-RPC initially, and let each node determine what it will implement.  Gob for speed, json-rpc for compatibility.

**Comment by cdunn2001** [comment]
For now, we support jsonrpc and http+gob. (It's important to remember that it's not just gob. The connection is established via http first. We _could_ provide a pure-gob codec someday.)
