### ISSUE TITLE
bsonrpc writes to a closed connection

### ISSUE THREAD

**Issue by erikstmartin** [skynetservices/skynet-archive#140]
we need to ensure the connection hasn't been closed by the client before writing to it

**Comment by skelterjohn** [comment]
This is generally impossible - it's racy. There is no way to guarantee that
the connection wasn't closed between when you last checked and when you
tried to write. The appropriate thing to do here is to attempt to write and
handle the error gracefully.

**Comment by erikstmartin** [comment]
fair enough. right now it doesn't panic and logs that it tried to write to a closed connection. so that may be the ideal solution
