### ISSUE TITLE
Dashboard websocket reconnect logic

### ISSUE THREAD

**Issue by erikstmartin** [skynetservices/skynet-archive#154]
if the dashboard looses it's connection to the websocket it needs to reconnect and update the view, right now when you disconnect it's unclear that you've disconnected you just receive no further updates

**Comment by elimisteve** [comment]
I'll look into this

**Comment by elimisteve** [comment]
Right now, if the WebSocket connection is broken, an error message is added to the DOM saying so.

@bketelsen Is the desired behavior something different? If so, let me know if you'd like me to work on this.

**Comment by erikstmartin** [comment]
I'd say to attempt to reconnect a couple of times automatically, and reset that counter each time a connection is established, so it's only after a specified timeout that it gives up and displays the message
