### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by bketelsen** [skynetservices/skynet-archive#16]
Build a Wiki page on how to get started.  Build a wiki page on how to contribute.

**Comment by cdunn2001** [comment]
I've done GitHub Wikis before. First, click Admin. Then check the Wiki box.

After that, I'll clone your Wiki and see whether I can issue pull-requests for Wiki updates. Or, just make me a "Collaborator" so that I can alter your Wiki pages directly.

**Comment by bketelsen** [comment]
added you as a collaborator.  Wiki pages already were there but empty.
