### ISSUE TITLE
Tell Steve whether to implement these logging-related features

### ISSUE THREAD

**Issue by elimisteve** [skynetservices/skynet-archive#174]
Suggestions from Eric regarding useful logging-related features I could add to Skynet:

```
yeah, any of that stuff we can provide by default would be great
service name, host:port, service version, region, request uuid
whether those fit into the ordinary property names, or we put them as tags, or they are part of the nested payload
just so that they are there so that we can easily search them
```

By adding extra parameters to `NewMongoSemanticLogger` (and perhaps `NewConsoleSemanticLogger`, etc), I should be able to log much of the above, including info from the RPC requests (stored in`RequestInfo` structs/objects/variables).

@bketelsen Give me the OK and I'll work on these things, and certainly let me know if you think there's some important data we should log and currently aren't. Thanks.

**Comment by erikstmartin** [comment]
Steve this is probably the highest priority, we definitely want to make sure log messages provide the: service name, version, host:port, region, request uuid, and maybe even the service uuid. This will help finding the log messages we need to troubleshoot problematic requests and services dramatically.
