### ISSUE TITLE
-region flag conflicts between sky command and client config

### ISSUE THREAD

**Issue by skelterjohn** [skynetservices/skynet-archive#176]
Both the sky command and the client config add a "region" flag to the flagset.

In the sky command, region is used to filter instances.

In the client config, it's used to self-identify the region for the purposes of choosing the best instance to send a request to.

One of these flags needs to be changed. Don't know to what.

**Comment by lfranchi** [comment]
I believe this was just fixed by @erikstmartin a few hours ago.
