### ISSUE TITLE
Install fails as Doozer can't compile

### ISSUE THREAD

**Issue by Lazarus404** [skynetservices/skynet-archive#179]
On executing the following (as listed in the wiki)

go get github.com/4ad/doozer
go get github.com/4ad/doozerd

Go throws an error stating

go/src/pkg/github.com/4ad/doozer/msg.pb.go:10: undefined: proto.GetString

Without Doozer, I can't run SkyNet :-(

**Comment by erikstmartin** [comment]
I'm working on fixing this today, we're going to fork the doozer dependencies so that we can ensure they work with skynet.

**Comment by srid** [comment]
the [official install instructions](https://github.com/skynetservices/skynet/wiki/Development-Environment-Setup) does not work for this reason. 

> go/src/pkg/github.com/4ad/doozer/msg.pb.go:10: undefined: proto.GetString

this particular issue was fixed in repos like github.com/ActiveState/doozerd

**Comment by Lazarus404** [comment]
Hi Sridhar,

You're using the wrong version of Doozer.  There's a version in the skynetservices Github account.

Lee

**Comment by skelterjohn** [comment]
I believe skynet should reference the correct version of doozer - it looks
like the docs are out of date. doing a "go get
github.com/skynetservices/skynet" should install everything you need.

**Comment by erikstmartin** [comment]
We have forked doozer into our GitHub organization, so this should no longer be a problem.
