### ISSUE TITLE
Problem with GetWidgets/router in examples

### ISSUE THREAD

**Issue by cdunn2001** [skynetservices/skynet-archive#19]
I have a problem compiled examples:

```
skynet/$ gb
(in examples/GetWidgets/initiators/mango) building cmd "mango"
(in examples/GetWidgets/router) building cmd "router"
router.go:15: can't find import: myStartup
```

By the way, I am using 'release' golang, not the latest, since I had a problem installing all libraries with the latest golang. But mango _requires_ the latest golang, so I had to switch to an early version of mango. I'm curious how you manage to test everything. What versions are you using? If you try `goinstall -clean -u` on all dependencies, does it still work for you? (If that breaks for you, soon you'll be able to use my fork of mango. I learned that `goinstall` looks for a `release` tag if it exists.)

**Comment by cdunn2001** [comment]
The problem appears to be the dependency order for **gb**. It worked after I built **myStartup** first. @paulbellamy never had the problem (for neither **router** nor his new **mangoInitiator**), so I think he must have had an existing **myStartup** built already. It fails on a fresh check-out.

I will see whether I can figure out how to fix the dependency order...

**Comment by paulbellamy** [comment]
Might be an issue with gb not finding the include.  When I run 'gb' in the project root it fails, however if I switch to the example directory it works, as below:

```
$ cd examples/GetWidgets && gb
(in watchers/generic) building cmd "generic"
(in initiators/mango) building cmd "mango"
(in router) building cmd "router"
(in watchers/reaper) building cmd "reaper"
(in initiators/web) building cmd "web"
(in service) building cmd "service"
Built 6 targets
```

**Comment by paulbellamy** [comment]
@cdunn2011 when it was working for me, I was building the example outside of the main project directory.

**Comment by cdunn2001** [comment]
Thanks, Paul. I'll submit this to go-gb. John will want to debug this, I'll bet.
