### ISSUE TITLE
We need a `release` branch.

### ISSUE THREAD

**Issue by cdunn2001** [skynetservices/skynet-archive#21]
Copied from issue#19:

> I am using 'release' golang, not the latest, since I had a problem installing all libraries with the latest golang. But mango requires the latest golang, so I had to switch to an early version of mango.

We've had a good discussion on `goinstall` in the [golang forum](https://groups.google.com/forum/#!topic/golang-nuts/S6YaCaKwfqA). `goinstall` will pull from a tag or branch called `release` if it exists. A `release` _branch_ is better than a tag because it's easier to move later. I just helped @paulbellamy with that in **mango**, and it works great.

It sounds a bit complicated, but that's only because golang changes so often. It also means that you can worry less about breaking things on `master`, since most people will be pulling from `release`.

**Comment by cdunn2001** [comment]
Created and pushed. Now, the tip of `release` is installed by **goinstall**. We can develop in `master` and merge to `release`.

Question: How do you test changes? We may need some adjustments. For example, **skygen** creates templates which depend on **GitHub**. We need a way to test using the local **skylib**. For now, I'll set it up to use an environment variable to replace `github.com/.../skylib` with just `skylib`.

Someday, we might add another branch for code that uses the latest version of **golang**.

**Comment by bketelsen** [comment]
Right now, I don't test anything - that's high on the list of stuff to fix.  I think this one may need a scripted test though.
