### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by bketelsen** [skynetservices/skynet-archive#22]
We need a plan for testing.  
1.  Generators
2.  Generated apps

Generator testing is pretty straightforward.  It either generates what we want or not.

Generated app testing is harder.  an idea
1. we create a skynet application much like the one in examples - with full tests - and use it as the extraction source for the generators

I'm open to any others.  Skynet won't be useful without a suite of good tests, so this is a priority.

**Comment by cdunn2001** [comment]
I'm working on it. The biggest problem for me is the most basic: How to use more than one version of skynet locally. I think that the answer is for devs to rely on `$GOPATH`, while non-devs can still use `goinstall github.com/bketelsen/skynet/...` automatically.

I have done lots of experimenting over the weekend (with the many idiosyncrasies of both **goinstall** and **gb**) and I hope to have a pull-request ready today.

**Comment by cdunn2001** [comment]
> we create a skynet app.... and use it as the extraction source for the generators.

Do you mean to compare the generated source code byte-for-byte against the example that we create? Yes, that would work.

**Comment by bketelsen** [comment]
What if we create a skynet mesh as our "master", and build an extractor to extract the pattern into the generator. It might make testing easier.  We'll build the mesh tests into the master app, and extract those tests into the template too.   This is a really hard problem to solve.
