### ISSUE TITLE
Generator

### ISSUE THREAD

**Issue by bketelsen** [skynetservices/skynet-archive#23]
Change the generator to be interactive.  Instead of a bunch of ugly and hard to remember command line flags, let's use an interactive generator that builds up enough information to make a skynet mesh.  This might be the highest bang for the buck right now.

**Comment by cdunn2001** [comment]
Might be high bang-for-buck, but I don't know what you mean by interactive. Do you mean Q&A via a command-line tool?

**Comment by bketelsen** [comment]
Yes - Ask questions, prompt for answer.  Receive interactive input from the user.  Store all interactive input until questions have been answered, then generate a Skynet mesh.

**Comment by cdunn2001** [comment]
A simple Ruby or Python script is a good start then.

**Comment by bketelsen** [comment]
Gack.  It's just as simple to write a simple Go script :)  I was thinking of just changing Skygen so that if there were no command line flags given, it would ask nicely with good prompts.

**Comment by cdunn2001** [comment]
Gack? I thought you knew Ruby. I can't believe you're using Ruby for web-dev and Go for a simple script. It should be the other way round!

I guess you want to query for the eventual components of the service request and response structs. Is that the idea?

**Comment by bketelsen** [comment]
I do know Ruby.. but the Skygen code is already in Go.  I was thinking like this:

What name for your service:  BriansCoolAPI

Do you need initiators? {y/N}  Y

etc.

**Comment by cdunn2001** [comment]
I don't think we should be afraid of other languages, especially for proto-typing. We are already using bash and make, plus a C-compiler for Go, and those imply the existence of perl, python, and probably ruby. One advantage of Go over Ruby for web-dev is that you can push a fully-compiled application. You do not need a Go compiler on the host. But we are dealing with source-code, so we know we have a full compilation environment. When we decide we need type-safety, I can usually translate between languages much faster than I can write the original code.

Anyway, just type up a typical session. It should be simple to code.
