### ISSUE TITLE
Introduce via 'example'. Describe skygen in wiki.

### ISSUE THREAD

**Issue by cdunn2001** [skynetservices/skynet-archive#25]
Brian, I think we should keep the README as simple as possible. We can skip the skygen/gb step by showing how to install/run GetWidgets or some other example. We can add tons of comments to that example for clarity.

Skygen can then be delineated on its own Wiki page, in much greater depth. Ok?

**Comment by bketelsen** [comment]
I want to change skygen completely -- see my previous issue.  Let's hold off on read me changes until skygen changes.

**Comment by cdunn2001** [comment]
I see. You don't see the system being used without skygen. Sort of like protocol-buffers -- They can work if you just set up your own bindings, but the authors expect you to write some JSON files to describe your protocols and let them do the rest of the work.

I'm getting more and more around at the golang folks. Since we separate pkg from cmd, the cmd has to mention github in its package import statement. Somebody made a big mistake there.
