### ISSUE TITLE
Add more initiator examples

### ISSUE THREAD

**Issue by bketelsen** [skynetservices/skynet-archive#27]
Add Twister, Web.Go, Resque and Stomp initiator examples

**Comment by cdunn2001** [comment]
I think we need to prioritize other transport protocols over this. Otherwise, we could have a lot more work to do later. I think we can re-factor most of the protocol-specific work into skylib. No?

**Comment by bketelsen** [comment]
I agree on the prioritization of transports first.   Protocol specific stuff, I'm not sure -- probably we can put it in skylib, but I'd have to think hard about it.  Skylib would be ideal, certainly.  But on the service side... it could get confusing.  Prototyping may solve this.

**Comment by cdunn2001** [comment]
> Prototyping may solve this.

?...  Do you mean by defining a protocol somehow, and letting a generator generate appropriate code? Hmmm.

**Comment by bketelsen** [comment]
my worry is that the way the code stands now, the transport mechanism for RPC is tied directly into the generated code.  Abstracting it out into sky lib would be idea, but I can't see how that would work without trying it.  That's all I'm saying.

**Comment by cdunn2001** [comment]
Oh, "prototyping" as in trying something to see what it looks like. Great! I love that. Big fan. Concrete implementations are much easier to argue over. I thought you were referring to a CS concept, like JavaScript prototype-based OOP.

**Comment by cdunn2001** [comment]
Lots of progress with a simple initiator and jsonrpc, but there is a bug. I won't have time to work on this until Saturday, unfortunately, so I'm afraid the new guy and I will have conflicts. Oh, well.
