### ISSUE TITLE
Abstract configuration (currently doozer)

### ISSUE THREAD

**Issue by cdunn2001** [skynetservices/skynet-archive#29]
Let's abstract out the doozer calls, so that we do not depend on doozer for testing.

**Comment by bketelsen** [comment]
This is a duplicate of issue #9

**Comment by cdunn2001** [comment]
Oops. Now I understand what you meant there. I thought there was something magical. I guess that's the first thing to do then.

We may want to abstract out the HTTP transport too, eventually. `DialHTTP` does not exist for **jsonrcp**, e.g.

**Comment by bketelsen** [comment]
Yes, we could even use NetChannels in Go if we wanted.
