### ISSUE TITLE
Doozer hardening

### ISSUE THREAD

**Issue by bketelsen** [skynetservices/skynet-archive#46]
DzNS doesn't remove downed instances.  Harden our doozer discovery implementation

Once DzNS has been setup ensure that we handle BootUri's properly and have environment variables to support them.

Ensure that we handle doozer connection failures, and find a new master if doozer can only write to master.

When doozer instances die and are restarted they loose all information, we need to make sure they reregister themselves.

**Comment by erikstmartin** [comment]
adding the vagrant nodes to /ctl/cal was not happening properly, which made it appear as if doozer wasn't handling failure well, this has been tested i have killed doozer nodes while running vagranttests and no lost requests
