### ISSUE TITLE
Timeouts

### ISSUE THREAD

**Issue by bketelsen** [skynetservices/skynet-archive#47]
Create a library to enable timeouts on all RPC calls, configurable at the client.

**Comment by bketelsen** [comment]
Is this close-able?

**Comment by skelterjohn** [comment]
I don't believe anything in the client package does this right now.

It might be useful to have both timeouts and secondary requests. That is, if you don't hear back in X seconds, send out another call to another instance and take the first result.

**Comment by bketelsen** [comment]
this is closable, and perhaps a duplicate of the one that was just closed.  SendOnce works and Send supports timeouts.
