### ISSUE TITLE
Web UI

### ISSUE THREAD

**Issue by bketelsen** [skynetservices/skynet-archive#51]
Show topology of the running services:

Datacenters
Hosts
Services by Service Version

At service version level, show metrics on response times.

Embed Graphite style dashboard for response time and request count monitoring, individually by service and aggregated by data center.

**Comment by erikstmartin** [comment]
The base of this is completed, although we plan on adding graphs and other cool features, i'm going to close this ticket and allow us to open tickets and prioritize each of those separately.
