### ISSUE TITLE
Configurable Retry

### ISSUE THREAD

**Issue by bketelsen** [skynetservices/skynet-archive#54]
Service should be marked as re-tryable.  if service call fails, try again, up to limit or timeout.

**Comment by skelterjohn** [comment]
Currently you can set retry and giveup timeout durations. To make a call, you can call .SendOnce() if you want to avoid retries, and it will timeout after giveup time has passed. If you call .Send(), it will send a request to a different instance every time retry time has passed, until a response is received or giveup time has passed.

This sound ok?

**Comment by bketelsen** [comment]
Yes, that's perfect.  I think we can close this issue.
