### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by bketelsen** [skynetservices/skynet-archive#55]
Create interface for remote logging, and single implementation using mongodb capped collection.  Interface should allow any implementation, first impl will be MongoDB capped collection.

Build Log viewer with searching into web UI.

**Comment by skelterjohn** [comment]
I'm going to grab this one as my first major task. Sticking my nose in all over the place to add logging hooks should help me get a better view overall.

**Comment by bketelsen** [comment]
can we close this with the current implementation?

**Comment by skelterjohn** [comment]
The logging works, but there is nothing for easy viewing. Also, I don't believe I'm the right person to work on that.

**Comment by bketelsen** [comment]
Then I'm closing this and will open a new ticket for logging viewer.  Perfect, thanks!
