### ISSUE TITLE
Refactor Prototype Code

### ISSUE THREAD

**Issue by bketelsen** [skynetservices/skynet-archive#59]
Much of this code is prototype quality.  Refactor extensively.  Fix pools, fix redundancy, fix inefficiencies, etc.

**Comment by skelterjohn** [comment]
I'd like to split up and relocate the skylib package into three different packages: "github.com/bketelsen/skynet", "github.com/bketelsen/skynet/client", and "github.com/bketelsen/skynet/service".

Opinions?

**Comment by bketelsen** [comment]
I think that makes good sense.    Go for it!

**Comment by skelterjohn** [comment]
https://github.com/bketelsen/skynet/pull/67

**Comment by bketelsen** [comment]
I'm going to leave this ticket open because there is likely plenty more refactoring to do.

**Comment by erikstmartin** [comment]
I'd say that all the refactoring is done, we are in a new feature, and bug fix mode now. Closing ticket
