### ISSUE TITLE
missing ProtoMessage error

### ISSUE THREAD

**Issue by qinhui99** [skynetservices/skynet-archive#61]
I try to install the skynet and get these errors:
# github.com/4ad/doozer

c:\go\src\pkg\github.com\4ad\doozer\conn.go:184: cannot use &t.req (type *reques
t) as type proto.Message in function argument:
        *request does not implement proto.Message (missing ProtoMessage method)
c:\go\src\pkg\github.com\4ad\doozer\conn.go:198: cannot use &r (type *response)
as type proto.Message in function argument:
        *response does not implement proto.Message (missing ProtoMessage method)

I use the google protobuf 2.4.1. Does the skynet need the lower version of protobuf ?

**Comment by skelterjohn** [comment]
The issue is an old version of github.com/4ad/doozerd. If you pull the
latest you'll get what you need.
- John

On Jun 30, 2012, at 10:29 PM, qinhui99
reply@reply.github.com
wrote:
