### ISSUE TITLE
Create viewer to look at logs

### ISSUE THREAD

**Issue by bketelsen** [skynetservices/skynet-archive#65]
Create web interface to review logs.  Should be searchable in various ways, and should live stream to the screen perhaps via websockets.

**Comment by bketelsen** [comment]
This will be the first web ui for skynet.  Use Bootstrap (from twitter) or something similar so we can have a consistent look and feel across all the UI's that we build.

**Comment by erikstmartin** [comment]
Some work has been done here, but it really needs to be refined, and tweaked

**Comment by bketelsen** [comment]
This is effectively done. Any new work can be in a new ticket for refinements.
