### ISSUE TITLE
Code Cleanup

### ISSUE THREAD

**Issue by bketelsen** [skynetservices/skynet-archive#7]
Code is generally ugly and needs refactoring, cleanup and full audit on error handling.  Very few circumstances should allow a panic, most should handle any error condition gracefully from the end-user's perspective.

**Comment by cdunn2001** [comment]
Changed **log** module.

```
skylib.LogError(skylib.DEBUG, msg)
// is now
skylib.LogDebug(msg)
```

This is similar to the Python **logging** module, Java **log4j**, etc.

**Comment by bketelsen** [comment]
Looks cleaner.
